# Generated by Django 3.0.7 on 2020-06-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('shares', models.DecimalField(decimal_places=6, max_digits=10)),
                ('avg_price_per_share', models.DecimalField(decimal_places=3, max_digits=9)),
            ],
        ),
    ]
